<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="DocumentManagement.aspx.cs" Inherits="DocumentManagement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
    </telerik:RadScriptManager>
    <link rel="Stylesheet" href="Styles/bootstrap.min.css" style="" />
    <link rel="Stylesheet" href="Styles/bootstrap.css" />
    <br />
    <br />
    <div align="center">
        <telerik:RadLabel ID="RadLabel1" runat="server">DOCUMENTS</telerik:RadLabel>
    </div>
    <div>
        <br />
        <telerik:RadDropDownList ID="RadDropDownList1" runat="server"></telerik:RadDropDownList>
        <br />
        <asp:FileUpload ID="FileUpload1" runat="server" />
        <asp:Button ID="btnUpload" runat="server" Text="Upload" OnClick="Upload" CssClass="btn-primary" />
    </div>
    <br />
    <br />
    <div>
        <telerik:RadGrid ID="RadGrid1" runat="server" AllowAutomaticDeletes="True" AllowAutomaticInserts="True" AllowAutomaticUpdates="True" AllowFilteringByColumn="True" AllowMultiRowEdit="True" AllowMultiRowSelection="True" AllowPaging="True" AllowSorting="True" AutoGenerateEditColumn="True" DataSourceID="SqlDataSource1" OnItemCommand="RadGrid1_ItemCommand" AutoGenerateDeleteColumn="True" Font-Size="Small">
            <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
            <ExportSettings>
                <Pdf PageWidth="">
                </Pdf>
            </ExportSettings>
            <ClientSettings>
                <Selecting AllowRowSelect="True" />
            </ClientSettings>
            <MasterTableView AutoGenerateColumns="False" DataKeyNames="DocID" DataSourceID="SqlDataSource1">
                <Columns>
                    <telerik:GridBoundColumn DataField="DocID" DataType="System.Int32" FilterControlAltText="Filter DocID column" HeaderText="DocID" ReadOnly="True" SortExpression="DocID" UniqueName="DocID" Visible="False">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="DocName" FilterControlAltText="Filter DocName column" HeaderText="DocName" SortExpression="DocName" UniqueName="DocName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="DocType" FilterControlAltText="Filter DocType column" HeaderText="DocType" SortExpression="DocType" UniqueName="DocType">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="EngenPrintersID" DataType="System.Int32" FilterControlAltText="Filter EngenPrintersID column" HeaderText="EngenPrintersID" SortExpression="EngenPrintersID" UniqueName="EngenPrintersID" Visible="False">
                    </telerik:GridBoundColumn>
                 <telerik:GridTemplateColumn>
                       <ItemTemplate>
                        <asp:LinkButton ID="lnkDownload" runat="server" Text="Download" OnClick="DownloadFile"
                        CommandArgument='<%# Eval("DocID") %>'></asp:LinkButton>
                        </ItemTemplate>
                 </telerik:GridTemplateColumn>
                </Columns>
            </MasterTableView>
        </telerik:RadGrid>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CompanyPrintersConnectionString %>" DeleteCommand="DELETE FROM [Documents] WHERE [DocID] = @DocID" InsertCommand="INSERT INTO [Documents] ([DocName], [DocType], [DocUrl], [EngenPrintersID]) VALUES (@DocName, @DocType, @DocUrl, @EngenPrintersID)" SelectCommand="SELECT * FROM [Documents]" UpdateCommand="UPDATE [Documents] SET [DocName] = @DocName, [DocType] = @DocType, [DocUrl] = @DocUrl, [EngenPrintersID] = @EngenPrintersID WHERE [DocID] = @DocID">
            <DeleteParameters>
                <asp:Parameter Name="DocID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="DocName" Type="String" />
                <asp:Parameter Name="DocType" Type="String" />
                <asp:Parameter Name="DocUrl" Type="Object" />
                <asp:Parameter Name="EngenPrintersID" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="DocName" Type="String" />
                <asp:Parameter Name="DocType" Type="String" />
                <asp:Parameter Name="DocUrl" Type="Object" />
                <asp:Parameter Name="EngenPrintersID" Type="Int32" />
                <asp:Parameter Name="DocID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>

