<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="UserList.aspx.cs" Inherits="UserList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server"></telerik:RadScriptManager>

    <telerik:RadWindowManager ID="RadWindowManager1" runat="server">
        <Windows>
            <telerik:RadWindow ID="RadWindow1" runat="server" NavigateUrl="UserManagemennt.aspx" Style="display: none;" RenderMode="Lightweight" OnClientClose="NationClientClose" MinHeight="500px" MinWidth="1000px" Modal="True" VisibleStatusbar="False">
            </telerik:RadWindow>
        </Windows>
    </telerik:RadWindowManager>

    <script type="text/javascript">
        function NationClientClose(sender, args) {
            window.location.reload();
        }
      
    </script>

    <script type="text/javascript">
        function OpenWindow() {
            var win = $find("<%=RadWindow1.ClientID %>");
            win.show();
            return false;
        }
    </script>
   
    <br />
    <br />
    <div align="center">
        <br />
        <br />
        <telerik:RadLabel ID="RadLabel1" runat="server">USER LIST</telerik:RadLabel>
        <br />
        <br />
        <telerik:RadGrid ID="RadGrid1" runat="server" DataSourceID="SqlDataSource1" AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True" Font-Size="Small" AllowAutomaticDeletes="True" AllowAutomaticInserts="True" AllowAutomaticUpdates="True" AllowMultiRowEdit="True" AllowMultiRowSelection="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True">
            <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
            <ExportSettings>
                <Pdf PageWidth="">
                </Pdf>
            </ExportSettings>

            <MasterTableView AutoGenerateColumns="False" DataKeyNames="UserID" DataSourceID="SqlDataSource1">
                <Columns>
                    <telerik:GridBoundColumn DataField="UserID" DataType="System.Int32" FilterControlAltText="Filter UserID column" HeaderText="UserID" ReadOnly="True" SortExpression="UserID" UniqueName="UserID" Visible="False">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="FirstName" FilterControlAltText="Filter FirstName column" HeaderText="FirstName" SortExpression="FirstName" UniqueName="FirstName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="LastName" FilterControlAltText="Filter LastName column" HeaderText="LastName" SortExpression="LastName" UniqueName="LastName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Email" FilterControlAltText="Filter Email column" HeaderText="Email" SortExpression="Email" UniqueName="Email">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="UserName" FilterControlAltText="Filter UserName column" HeaderText="UserName" SortExpression="UserName" UniqueName="UserName">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Password" FilterControlAltText="Filter Password column" HeaderText="Password" SortExpression="Password" UniqueName="Password">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="Address" FilterControlAltText="Filter Address column" HeaderText="Address" SortExpression="Address" UniqueName="Address">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="DOB" DataType="System.DateTime" FilterControlAltText="Filter DOB column" HeaderText="DOB" SortExpression="DOB" UniqueName="DOB">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="DesignationID" DataType="System.Int32" FilterControlAltText="Filter DesignationID column" HeaderText="DesignationID" SortExpression="DesignationID" UniqueName="DesignationID" Visible="False">
                    </telerik:GridBoundColumn>
                </Columns>
            </MasterTableView>
              <ClientSettings>
                     <Selecting AllowRowSelect="True" EnableDragToSelectRows="True"></Selecting>
                     <ClientEvents OnRowDblClick="RowDblClick"></ClientEvents>
                     <ClientEvents OnRowSelected="RowSelected" />
                      <Resizing AllowColumnResize="true" ResizeGridOnColumnResize="true" AllowResizeToFit="true" />
                 </ClientSettings>
        </telerik:RadGrid>
        <br />
        <br />
        <asp:LinkButton ID="lnkMetricGroup" Text="Add User" OnClientClick="return OpenWindow();" ButtoncssClass="MyButton" runat="server" Style="position: relative;" BackColor="#CCCCCC" BorderColor="Gray" ForeColor="#333333"></asp:LinkButton>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CompanyPrintersConnectionString %>" DeleteCommand="DELETE FROM [Users] WHERE [UserID] = @UserID" InsertCommand="INSERT INTO [Users] ([FirstName], [LastName], [Email], [UserName], [Password], [Address], [DOB], [DesignationID]) VALUES (@FirstName, @LastName, @Email, @UserName, @Password, @Address, @DOB, @DesignationID)" SelectCommand="SELECT * FROM [Users]" UpdateCommand="UPDATE [Users] SET [FirstName] = @FirstName, [LastName] = @LastName, [Email] = @Email, [UserName] = @UserName, [Password] = @Password, [Address] = @Address, [DOB] = @DOB, [DesignationID] = @DesignationID WHERE [UserID] = @UserID">
            <DeleteParameters>
                <asp:Parameter Name="UserID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="UserName" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="Address" Type="String" />
                <asp:Parameter DbType="Date" Name="DOB" />
                <asp:Parameter Name="DesignationID" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="FirstName" Type="String" />
                <asp:Parameter Name="LastName" Type="String" />
                <asp:Parameter Name="Email" Type="String" />
                <asp:Parameter Name="UserName" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="Address" Type="String" />
                <asp:Parameter DbType="Date" Name="DOB" />
                <asp:Parameter Name="DesignationID" Type="Int32" />
                <asp:Parameter Name="UserID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>

